# DroneHover-v0 TD3 최적화 설정 (연구에서 가장 일관된 성능)

environment:
  name: "DroneHover-v0"
  seed: 42

algorithm:
  name: "TD3"
  lr_actor: 0.0003
  lr_critic: 0.001
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  has_continuous_action_space: true
  hidden1: 512
  hidden2: 256
  init_w: 0.003
  policy_noise: 0.1
  noise_clip: 0.5
  policy_freq: 2
  exploration_noise: 0.1  # 드론 제어를 위한 적절한 탐험

network:
  hidden_dims: [512, 256]
  activation: "relu"

training:
  max_episodes: 3000
  update_interval: 2048
  eval_interval: 100
  save_interval: 300
  max_steps_per_episode: 8000

experiment:
  name: "drone_hover_td3"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/drone_hover_td3"

logging:
  tensorboard: false
  save_metrics: true
  use_wandb: true
  wandb_project: "rl-framework-drone-hover"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000