# Ant-v4 PPO 최적화 설정

environment:
  name: "Ant-v4"
  seed: 42

algorithm:
  name: "PPO"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.015
  train_policy_iters: 80
  train_value_iters: 80
  lam: 0.97
  has_continuous_action_space: true
  action_std_init: 0.6  # Ant에 적합한 exploration

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 2000
  update_interval: 2048
  eval_interval: 20
  save_interval: 200
  max_steps_per_episode: 1000

experiment:
  name: "ant-v4_ppo"
  seeds: [0, 1, 2, 3, 4]
  device: "cuda"
  save_dir: "results/ant-v4_ppo"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco-ant"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000