# Humanoid PPO 실험 설정 (복잡한 로봇팔/전신 로봇)

environment:
  name: "Humanoid-v4"
  seed: 42

algorithm:
  name: "PPO"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.01
  train_policy_iters: 80
  train_value_iters: 80
  lam: 0.97
  has_continuous_action_space: true
  action_std_init: 0.6

network:
  hidden_dims: [512, 512, 256]  # Humanoid는 더 복잡한 네트워크 필요
  activation: "tanh"

training:
  max_episodes: 10000  # 10M steps 목표
  max_steps_per_episode: 1000
  update_interval: 2048
  eval_interval: 50
  save_interval: 500
  log_interval: 25

experiment:
  name: "humanoid_ppo"
  seeds: [0, 1, 2, 3, 4]
  device: "cuda"
  save_dir: "results/humanoid_ppo"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 200
  use_wandb: true
  wandb_project: "rl-framework-mujoco-Humanoid"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000