# Humanoid-v4 SAC 최적화 설정

environment:
  name: "Humanoid-v4"
  seed: 42

algorithm:
  name: "SAC"
  lr_actor: 0.0003
  lr_critic: 0.0003
  lr_alpha: 0.0003
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  alpha: 0.2
  automatic_entropy_tuning: true
  target_entropy: -17  # -action_dim for Humanoid (17 actions)
  stable_update_size: 10000

network:
  hidden_dims: [256, 256]

training:
  max_episodes: 10000  # 10M steps 목표 (1000 * 10000)
  update_interval: 1
  eval_interval: 50
  save_interval: 500
  max_steps_per_episode: 1000

experiment:
  name: "humanoid-v4_sac"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/humanoid-v4_sac"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco-humanoid"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000