# LunarLanderContinuous A2C 실험 설정

environment:
  name: "LunarLanderContinuous-v3"
  seed: 42

algorithm:
  name: "A2C"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  entropy_coef: 0.01
  value_loss_coef: 0.5
  has_continuous_action_space: true
  action_std_init: 1.0

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 2000
  max_steps_per_episode: 1000
  update_interval: 5  # A2C는 n-step마다 업데이트
  eval_interval: 50
  save_interval: 500
  log_interval: 10

experiment:
  name: "lunarlander_a2c"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/lunarlander_a2c"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-lunarlandercontinuous"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000