# LunarLanderContinuous TRPO 실험 설정

environment:
  name: "LunarLanderContinuous-v3"
  seed: 42

algorithm:
  name: "TRPO"
  lr: 3e-4
  gamma: 0.99
  gae_lambda: 0.95
  max_kl: 0.01
  damping: 0.3
  has_continuous_action_space: true
  action_std_init: 0.8
  critic_iters: 80  # 가치 함수 업데이트 스텝 수

network:
  hidden_dims: [128, 128]
  activation: "tanh"

training:
  max_episodes: 4056
  update_interval: 512
  eval_interval: 10
  save_interval: 500

experiment:
  name: "lunarlandercontinuous-v3_trpo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/lunarlandercontinuous-v3_trpo"

logging:
  tensorboard: false
  save_metrics: true
  # wandb 설정
  use_wandb: True
  wandb_project: "rl-framework-lunarlandercontinuous"
  wandb_entity: "tatalintelli-university-of-seoul"  # wandb 사용자명 또는 팀명
  # 스텝 기반 로깅 설정
  enable_step_logging: true
  step_log_interval: 1000  # 모든 알고리즘에서 동일한 간격 사용 