# HalfCheetah A2C 실험 설정

# 환경 설정
environment:
  name: "HalfCheetah-v5"
  seed: 42

# 알고리즘 설정
algorithm:
  name: "A2C"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  has_continuous_action_space: true
  action_std_init: 0.8
  entropy_coef: 0.01
  value_loss_coef: 0.5

# 네트워크 설정
network:
  hidden_dims: [64, 64]
  activation: "tanh"

# 학습 설정
training:
  max_episodes: 1000
  max_steps_per_episode: 1000
  eval_interval: 50
  save_interval: 100
  log_interval: 10

# 실험 설정
experiment:
  name: "halfcheetah_a2c"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/halfcheetah_a2c"

# 로깅 설정
logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco-halfcheetah"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000