# LunarLanderContinuous DDPG 실험 설정

environment:
  name: "HalfCheetah-v4"
  seed: 42

algorithm:
  name: "DDPG"
  lr_actor: 0.001
  lr_critic: 0.001
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 128
  ou_theta: 0.15
  ou_mu: 0.0
  ou_sigma: 0.2
  has_continuous_action_space: true
  hidden1: 400
  hidden2: 300
  init_w: 0.003
  action_repeat: 1  # 액션 반복 횟수
  bn_use: false  # 입력 레이어에 배치 정규화 사용 여부
  noise_type: "gaussian"  # 'ou' 또는 'gaussian'
  exploration_std: 0.1  # 탐험을 위한 표준편차
  stable_update_size: 10000  # 안정적인 업데이트를 위한 크기
  

network:
  hidden_dims: [400, 300]
  activation: "relu"

training:
  max_episodes: 1000
  update_interval: 2048  # DDPG는 매 step마다 업데이트
  eval_interval: 10
  save_interval: 500

experiment:
  name: "halfcheetah-v4_ddpg"
  seeds: [42]
  device: "cuda"
  save_dir: "results/halfcheetah-v4_ddpg"

logging:
  tensorboard: false
  save_metrics: true
  # wandb 설정
  use_wandb: true
  wandb_project: "rl-framework-mujoco-HalfCheetah"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000