# HalfCheetah SAC 실험 설정

# 환경 설정
environment:
  name: "HalfCheetah-v5"
  seed: 42

# 알고리즘 설정
algorithm:
  name: "SAC"
  lr_actor: 0.0003
  lr_critic: 0.0003
  lr_alpha: 0.0003
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  alpha: 0.2
  automatic_entropy_tuning: true
  target_entropy: -6  # -action_dim for HalfCheetah (6 actions)
  stable_update_size: 10000

# 네트워크 설정
network:
  hidden_dims: [256, 256]

# 학습 설정
training:
  max_episodes: 1000
  update_interval: 2048  # SAC는 매 step마다 업데이트
  eval_interval: 10
  save_interval: 500

# 실험 설정
experiment:
  name: "halfcheetah-v4_sac"
  seeds: [0, 1, 2]  # 5개 시드로 통계적 유의성
  device: "cuda"
  save_dir: "results/halfcheetah-v4_sac"

# 로깅 설정
logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco-halfcheetah"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000