# LunarLanderContinuous TRPO 실험 설정

environment:
  name: "HalfCheetah-v5"
  seed: 42

algorithm:
  name: "TRPO"
  lr: 3e-4
  gamma: 0.99
  gae_lambda: 0.95
  max_kl: 0.01
  damping: 0.3
  has_continuous_action_space: true
  action_std_init: 1.0
  critic_iters: 80  # 가치 함수 업데이트 스텝 수

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 1000
  update_interval: 2048
  eval_interval: 10
  save_interval: 500

experiment:
  name: "halfcheetah-v4_trpo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/halfcheetah-v4_trpo"

logging:
  tensorboard: false
  save_metrics: true
  # wandb 설정
  use_wandb: True
  wandb_project: "rl-framework-mujoco-HalfCheetah"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000