# Walker2d-v5 DDPG 최적화 설정

environment:
  name: "Walker2d-v5"
  seed: 42

algorithm:
  name: "DDPG"
  lr_actor: 0.0003
  lr_critic: 0.001
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  ou_theta: 0.15
  ou_mu: 0.0
  ou_sigma: 0.15  # Walker2d에 적합한 탐험 노이즈
  has_continuous_action_space: true
  hidden1: 400
  hidden2: 300
  init_w: 0.003
  action_repeat: 1
  bn_use: true
  noise_type: "ou"
  exploration_std: 0.1
  stable_update_size: 10000

network:
  hidden_dims: [400, 300]
  activation: "relu"

training:
  max_episodes: 1500
  update_interval: 2048
  eval_interval: 15
  save_interval: 150
  max_steps_per_episode: 1000

experiment:
  name: "walker2d-v4_ddpg"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/walker2d-v4_ddpg"

logging:
  tensorboard: false
  save_metrics: true
  use_wandb: true
  wandb_project: "rl-framework-mujoco-walker2d"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000