# Walker2d-v5 PPO 최적화 설정

environment:
  name: "Walker2d-v5"
  seed: 42

algorithm:
  name: "PPO"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.015
  train_policy_iters: 80
  train_value_iters: 80
  lam: 0.97
  has_continuous_action_space: true
  action_std_init: 0.6  # Walker2d에 맞춘 exploration

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 1500
  update_interval: 2048
  eval_interval: 15
  save_interval: 150
  max_steps_per_episode: 1000

experiment:
  name: "walker2d-v4_ppo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/walker2d-v4_ppo"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco-walker2d"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000