# Walker2d-v5 TRPO 최적화 설정

environment:
  name: "Walker2d-v5"
  seed: 42

algorithm:
  name: "TRPO"
  lr: 3e-4
  gamma: 0.99
  gae_lambda: 0.95
  max_kl: 0.01
  damping: 0.3
  has_continuous_action_space: true
  action_std_init: 0.6
  critic_iters: 80

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 1500
  update_interval: 2048
  eval_interval: 15
  save_interval: 150
  max_steps_per_episode: 1000

experiment:
  name: "walker2d-v4_trpo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/walker2d-v4_trpo"

logging:
  tensorboard: false
  save_metrics: true
  use_wandb: true
  wandb_project: "rl-framework-mujoco-walker2d"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000