# FetchReach-v4 TD3 최적화 설정 (로봇팔 manipulation)

environment:
  name: "FetchReach-v4"
  seed: 42

algorithm:
  name: "TD3"
  lr_actor: 0.0003
  lr_critic: 0.001
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  has_continuous_action_space: true
  hidden1: 400
  hidden2: 300
  init_w: 0.003
  policy_noise: 0.1
  noise_clip: 0.5
  policy_freq: 2
  exploration_noise: 0.05  # 로봇팔은 정밀한 제어 필요

network:
  hidden_dims: [400, 300]  # Robotics manipulation에 효과적
  activation: "relu"

training:
  max_episodes: 5000
  update_interval: 2048
  eval_interval: 100
  save_interval: 500
  max_steps_per_episode: 50

experiment:
  name: "fetchpush-v3_td3"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/fetchpush-v3_td3"

logging:
  tensorboard: false
  save_metrics: true
  use_wandb: true
  wandb_project: "rl-framework-robotics-fetchpush"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 500