# CartPole A2C 실험 설정

environment:
  name: "CartPole-v1"
  seed: 42

algorithm:
  name: "A2C"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  entropy_coef: 0.01
  value_loss_coef: 0.5
  has_continuous_action_space: false
  action_std_init: 0.6

network:
  hidden_dims: [128, 128]
  activation: "tanh"

training:
  max_episodes: 1000
  max_steps_per_episode: 500
  update_interval: 5  # A2C는 n-step마다 업데이트
  eval_interval: 50
  save_interval: 300
  log_interval: 10

experiment:
  name: "cartpole_a2c"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/cartpole_a2c"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-cartpole"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000