# CartPole SQL 실험 설정 (이산 행동공간)

# 환경 설정
environment:
  name: "CartPole-v1"
  seed: 42

# 알고리즘 설정
algorithm:
  name: "SQL"
  lr_actor: 3e-4
  lr_critic: 3e-4
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  temperature: 1.0
  has_continuous_action_space: false
  stable_update_size: 1000

# 네트워크 설정
network:
  hidden_dims: [256, 256]

# 학습 설정
training:
  max_episodes: 1000
  max_steps_per_episode: 500
  eval_interval: 50
  save_interval: 100
  log_interval: 10

# 실험 설정
experiment:
  name: "cartpole_sql"
  seeds: [0, 1, 2]
  device: "cpu"
  save_dir: "results/cartpole_sql"

# 로깅 설정
logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 50
  use_wandb: false
  enable_step_logging: true
  step_log_interval: 1000