# Ant DDPG 실험 설정 (사족보행 로봇)

environment:
  name: "Ant-v4" 
  seed: 42

algorithm:
  name: "DDPG"
  lr_actor: 1e-4
  lr_critic: 1e-3
  gamma: 0.99
  tau: 0.005
  buffer_size: 1000000
  batch_size: 256
  ou_theta: 0.15
  ou_mu: 0.0
  ou_sigma: 0.2
  has_continuous_action_space: true
  hidden1: 400
  hidden2: 300
  init_w: 0.003

network:
  hidden_dims: [400, 300]
  activation: "relu"

training:
  max_episodes: 2000
  max_steps_per_episode: 1000
  update_interval: 1000
  eval_interval: 50
  save_interval: 500
  log_interval: 10

experiment:
  name: "ant_ddpg"
  seeds: [0, 1, 2, 3, 4]
  device: "cuda"
  save_dir: "results/ant_ddpg"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 100
  use_wandb: true
  wandb_project: "rl-framework-mujoco"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 1000