# LunarLanderContinuous PPO 실험 설정

environment:
  name: "LunarLanderContinuous-v3"
  seed: 42

algorithm:
  name: "PPO"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.03
  train_policy_iters: 50
  train_value_iters: 80
  lam: 0.97
  has_continuous_action_space: true
  action_std_init: 1.0

network:
  hidden_dims: [128, 128]
  activation: "tanh"

training:
  max_episodes: 500
  # max_steps_per_episode: 1000  # PPO는 max_steps_per_episode를
  update_interval: 2048
  eval_interval: 10           # 10 epoch 단위
  save_interval: 1000000

experiment:
  name: "lunarlandercontinuous_ppo"
  seeds: [0, 1, 2, 3, 4]
  device: "cuda"
  save_dir: "results/lunarlandercontinuous_ppo"

logging:
  tensorboard: false
  save_metrics: true
  # wandb 설정
  use_wandb: True
  wandb_project: "rl-framework-lunarlandercontinuous"
  wandb_entity: "tatalintelli-university-of-seoul"  # wandb 사용자명 또는 팀명
  # 스텝 기반 로깅 설정
  enable_step_logging: true
  step_log_interval: 100  # 모든 알고리즘에서 동일한 간격 사용 