_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.18
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
algorithm:
    value:
        action_std_init: 0.6
        damping: 0.1
        gae_lambda: 0.95
        gamma: 0.99
        has_continuous_action_space: true
        lr: "3e-4"
        max_kl: 0.01
        name: TRPO
environment:
    value:
        name: LunarLanderContinuous-v3
        seed: 42
experiment:
    value:
        device: cpu
        name: lunarlandercontinuous_trpo
        save_dir: results/lunarlandercontinuous_trpo
        seeds:
            - 0
            - 1
            - 2
logging:
    value:
        plot_interval: 50
        save_metrics: true
        tensorboard: false
        use_wandb: true
        wandb_entity: tatalintelli-university-of-seoul
        wandb_project: rl-framework-lunarlandercontinuous
network:
    value:
        activation: tanh
        hidden_dims:
            - 64
            - 64
training:
    value:
        eval_interval: 10
        log_interval: 10
        max_episodes: 2000
        max_steps_per_episode: 1000
        save_interval: 1000
        update_interval: 2048
