# FetchReach-v4 PPO 최적화 설정 (로봇팔 manipulation)

environment:
  name: "FetchReach-v4"
  seed: 42

algorithm:
  name: "PPO"
  lr_actor: 3e-4
  lr_critic: 1e-3
  gamma: 0.99
  gae_lambda: 0.95
  clip_ratio: 0.2
  target_kl: 0.015
  train_policy_iters: 80
  train_value_iters: 80
  lam: 0.97
  has_continuous_action_space: true
  action_std_init: 0.3  # 로봇팔은 작은 exploration

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 5000
  update_interval: 2048  # PPO는 배치 업데이트
  eval_interval: 100
  save_interval: 500
  max_steps_per_episode: 50

experiment:
  name: "fetchreach-v4_ppo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/fetchreach-v4_ppo"

logging:
  tensorboard: false
  save_metrics: true
  plot_interval: 200
  use_wandb: true
  wandb_project: "rl-framework-robotics-fetchreach"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 500