# FetchReach-v4 TRPO 최적화 설정 (로봇팔 manipulation)

environment:
  name: "FetchReach-v4"
  seed: 42

algorithm:
  name: "TRPO"
  lr: 3e-4
  gamma: 0.99
  gae_lambda: 0.95
  max_kl: 0.01
  damping: 0.3
  has_continuous_action_space: true
  action_std_init: 0.3  # 로봇팔은 작은 exploration
  critic_iters: 80

network:
  hidden_dims: [256, 256]
  activation: "tanh"

training:
  max_episodes: 5000
  update_interval: 2048
  eval_interval: 100
  save_interval: 500
  max_steps_per_episode: 50

experiment:
  name: "fetchreach-v4_trpo"
  seeds: [0, 1, 2]
  device: "cuda"
  save_dir: "results/fetchreach-v4_trpo"

logging:
  tensorboard: false
  save_metrics: true
  use_wandb: true
  wandb_project: "rl-framework-robotics-fetchreach"
  wandb_entity: "tatalintelli-university-of-seoul"
  enable_step_logging: true
  step_log_interval: 500