_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.8.18
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
algorithm:
    value:
        batch_size: 64
        buffer_size: 1000000
        gamma: 0.99
        has_continuous_action_space: true
        hidden1: 400
        hidden2: 300
        init_w: 0.003
        lr_actor: 0.0001
        lr_critic: 0.001
        name: DDPG
        ou_mu: 0
        ou_sigma: 0.2
        ou_theta: 0.15
        tau: 0.001
environment:
    value:
        name: LunarLanderContinuous-v3
        seed: 42
experiment:
    value:
        device: cpu
        name: lunarlandercontinuous_ddpg
        save_dir: results/lunarlandercontinuous_ddpg
        seeds:
            - 0
            - 1
            - 2
logging:
    value:
        plot_interval: 50
        save_metrics: true
        tensorboard: false
        use_wandb: true
        wandb_entity: tatalintelli-university-of-seoul
        wandb_project: rl-framework-lunarlandercontinuous
network:
    value:
        activation: relu
        hidden_dims:
            - 400
            - 300
training:
    value:
        eval_interval: 10
        log_interval: 10
        max_episodes: 1000
        max_steps_per_episode: 1000
        save_interval: 500
        update_interval: 500
